version: '3.4'

services:
  taxiservice-carcatalog:
    image: taxiservicecontainerregistry.azurecr.io/taxiservicecarcatalog
    build:
      context: .
      dockerfile: TaxiService.CarCatalog/Dockerfile
    ports:
      - "8080:80"

  taxiservice-discount:
    image: taxiservicecontainerregistry.azurecr.io/taxiservicediscount
    build:
      context: .
      dockerfile: TaxiService.Discount/Dockerfile
    ports:
      - "8081:80"

  taxiservice-news:
    image: taxiservicecontainerregistry.azurecr.io/taxiservicenews
    build:
      context: .
      dockerfile: TaxiService.News/Dockerfile
    ports:
      - "8082:80"

  taxiservice-order:
    image: taxiservicecontainerregistry.azurecr.io/taxiserviceorder
    build:
      context: .
      dockerfile: TaxiService.Order/Dockerfile
    ports:
      - "8083:80"

