version: '3.4'

services:
  taxiservice-carcatalog:
    image: lushchevskyi/taxi-service.carcatalog
    build:
      context: .
      dockerfile: TaxiService.CarCatalog/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro


  taxiservice-discount:
    image: lushchevskyi/taxi-service.discount
    build:
      context: .
      dockerfile: TaxiService.Discount/Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro


  taxiservice-news:
    image: lushchevskyi/taxi-service.news
    build:
      context: .
      dockerfile: TaxiService.News/Dockerfile
    ports:
      - "8082:80"

  taxiservice-order:
    image: lushchevskyi/taxi-service.order
    build:
      context: .
      dockerfile: TaxiService.Order/Dockerfile
    ports:
      - "8083:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro


  taxiservice-identity:
    image: lushchevskyi/taxi-service.identity
    build:
      context: .
      dockerfile: TaxiService.Identity/Dockerfile
    ports:
      - "8084:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro


  taxiservice-apigateway:
    image: lushchevskyi/taxi-service.apigateway
    build:
      context: .
      dockerfile: TaxiService.APIGateway/Dockerfile
    ports:
      - "8085:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro


    links:
      - taxiservice-carcatalog
      - taxiservice-discount
      - taxiservice-news
      - taxiservice-order
      - taxiservice-identity
    depends_on:
      - taxiservice-carcatalog
      - taxiservice-discount
      - taxiservice-news
      - taxiservice-order
      - taxiservice-identity

