version: '3.4'

services:
  taxiservice.carcatalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  taxiservice.discount:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  taxiservice.news:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  taxiservice.order:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

