// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxiService.Identity.Data;

namespace TaxiService.Identity.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20201220195807_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("TaxiService.Identity.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "eece6dd1-4f0f-45d6-b4f8-2ae0a6ebb6cd",
                            Password = "Pass1",
                            Username = "Test1"
                        },
                        new
                        {
                            UserId = "7519cf1f-9af7-4af1-8752-e91930069a87",
                            Password = "Pass2",
                            Username = "Test2"
                        });
                });

            modelBuilder.Entity("TaxiService.Identity.Models.UserRole", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RoleId = "26bffe7b-bf06-4641-b6de-9e4fdba32b7e",
                            Role = "Admin"
                        },
                        new
                        {
                            RoleId = "91d1232d-a1c4-4dc0-9b0c-a26d1de2f628",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("TaxiService.Identity.Models.User", b =>
                {
                    b.HasOne("TaxiService.Identity.Models.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
