// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxiService.Identity.Data;

namespace TaxiService.Identity.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20201220190814_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("TaxiService.Identity.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "154d0ccc-599c-456a-b311-5d298bc13b5b",
                            Password = "Pass1",
                            Username = "Test1"
                        },
                        new
                        {
                            UserId = "72f406a3-bd18-47bf-8170-d96b5b3949f6",
                            Password = "Pass2",
                            Username = "Test2"
                        });
                });

            modelBuilder.Entity("TaxiService.Identity.Models.UserRole", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RoleId = "eb04f571-d6a6-49b0-9194-61f268f91d72",
                            Role = "Admin"
                        },
                        new
                        {
                            RoleId = "4a9906ca-9824-4ea0-8bdf-480489e55d59",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("TaxiService.Identity.Models.User", b =>
                {
                    b.HasOne("TaxiService.Identity.Models.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
