// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxiService.Identity.Data;

namespace TaxiService.Identity.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("TaxiService.Identity.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "734da69e-23f2-4cb8-a5dc-650ef83cd7d3",
                            Password = "Pass1",
                            Username = "Test1"
                        },
                        new
                        {
                            UserId = "0ca7b1ed-5ab7-48f9-9fba-013759793e81",
                            Password = "Pass2",
                            Username = "Test2"
                        });
                });

            modelBuilder.Entity("TaxiService.Identity.Models.UserRole", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RoleId = "b0b9cafd-bd60-42b7-91d0-5fd29acdb683",
                            Role = "Admin"
                        },
                        new
                        {
                            RoleId = "43f5f111-3164-411f-bee5-bb358b5043ed",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("TaxiService.Identity.Models.User", b =>
                {
                    b.HasOne("TaxiService.Identity.Models.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
